- style-guide/README.md
- style-guide/a-l-style-guidelines.md
- style-guide/basic-writing-guidelines.md
- style-guide/m-z-style-guidelines.md
- style-guide/terminology-guidelines.md
I converted most of the style guide to Markdown and have uploaded those files here.
> Migrate style guide to GitHub

- tools/editorial-review-process.md
- tools/technical-review-process.md
starting points for review/udpate as the process evolves.
> Add files for technical and editorial review process. These are

- tools/add-github-links-to-docs.rst
Documentation for adding Edit on GitHub or Submit an issue links to Sphinx documentation projects build by deconst.
> Add documentation for adding GitHub links

- style-guide/basic-writing-guidelines.md
- style-guide/terminology-guidelines.md
Added some guidelines and terms from OpenStack guidelines
> add-negative-terms

- quality/PULL_REQUEST_TEMPLATE.md
Draft PULL_REQUEST_TEMPLATE.md for quality checklist
> Draft PULL_REQUEST_TEMPLATE.md

- style-guide/m-z-style-guidelines.md
Based on API reference meeting with Cat, Catherine, and Margaret
> update parameter guidelines

- doc/rpc-other/HowTo-RPCDocs/HowTo-BestPractices.rst
> Remove artifacts from RST conversion

- doc/tools/nexus-deletion.md
> Add nexus-deletion.md per Ash's suggestion.

- doc/contributor-collateral/docteam-FAQ.rst
Trying to fix formatting weirdness with better consistency in bullet formatting.
> Fixing some formatting weirdness

- doc/contributor-collateral/privatecloud-docteam-FAQ.rst
> Renaming the doc for private cloud purposes

- doc/tools/publishing.rst
Clarify that content describes how to configure development and production builds.
> Updated title

- doc/rpc/HowTo-OpenStack-On-RAX-Cloud-Ubuntu.rst
Fix diagram link and update title.
> Fix diagram link

- doc/rpc/HowTo-OpenStack-On-RAX-Cloud-Ubuntu.rst
Minor updates to the instructions
> Update OpenStack on Ubuntu servers instructions

- doc/tools/internal-publish-script.rst
When the new publish script is finished, update the path in the tools doc.
> Update publish.sh script path

- doc/spelling_wordlist.txt
- doc/tools/publishing.rst
Add changes that didn't merge in
https://github.com/rackerlabs/docs-rackspace/pull/222
Partial https://github.com/rackerlabs/docs-rackspace/issues/185
> Revise the publishing procedure

- doc/style-guide/README.rst
- doc/style-guide/a-l-style-guidelines.rst
- doc/style-guide/basic-writing-guidelines.rst
- doc/style-guide/index.rst
- doc/style-guide/m-z-style-guidelines.rst
I made a few updates to the "Basic writing guidelines" section to fix links and change the formatting of notes in tables. I updated other files for link references, and I slightly updated the index and readme files.
> Style guide edits: basic writing guidelines

- doc/style-guide/a-l-style-guidelines.rst
- doc/style-guide/basic-writing-guidelines.rst
- doc/style-guide/m-z-style-guidelines.rst
I updated links, added references, and fixed notes in tables. Will resume work tomorrow!
> Fix links and nits in style guide A-Z through Time

- doc/style-guide/a-l-style-guidelines.rst
- doc/style-guide/alphabetical-terms.rst
- doc/style-guide/basic-writing-guidelines.rst
- doc/style-guide/m-z-style-guidelines.rst
- doc/style-guide/release-notes-guidelines.rst
- doc/style-guide/revision-history.rst
- doc/style-guide/screenshot-diagram-guidelines.rst
- doc/style-guide/trademarks.rst
> Finish style guide fixes

- doc/contributor-collateral/privatecloud-docteam-FAQ.rst
> Remove Kyle Laffoon and add Laura Santamaria

- doc/contributor-collateral/privatecloud-docteam-FAQ.rst
Change to note there is only a doc folder - no longer an internal folder.
Also update the list of what is published externally and what is published internally.
> Update documentation locations

- doc/style-guide/index.rst
License added to share with others.
> Add Creative Commons license to the Style Guide

- doc/style-guide/a-l-style-guidelines.rst
- doc/style-guide/basic-writing-guidelines.rst
- doc/style-guide/index.rst
- doc/style-guide/m-z-style-guidelines.rst
Streamlined some topics to make them easier for contributors to consume. Also in preparation for breaking all the topics out into separate files.
> Streamlined some style guide topics

- .gitignore
Updated the .gitignore file to match the one in `docs-repo-template`.
> updating the .gitignore file

- doc/style-guide/index.rst
- doc/style-guide/quickstart.rst
Moved section descriptions to intro page in order to streamline quickstart
> Tweaked main index and quickstart

- doc/style-guide/style/code-examples.rst
Updates with new ruling based on: https://github.com/rackerlabs/docs-workstream/issues/215
This has already been updated in the RPC CONTRIBUTING file also.
Also corrected spelling duplicate.
> Update with code-block for RST

- doc/style-guide/markup-guidelines.rst
* INFODEV-339
* We use Kramdown syntax, so add resources
* Fix wiki link
* Reflow long lines
> Add Kramdown references

- doc/style-guide/terminology/concise-terms.rst
Add "reach out to" > "contact"
> Add term to concise terms table

- doc/index.rst
> Change main index so that only the Style Guide is published to

- doc/index.rst
Reverts rackerlabs/docs-rackspace#347
> Revert "Change main index so that only the Style Guide is published to"

- doc/style-guide/style/capitalization.rst
for new capitalization guidelines sections - for job titles and team names
> Add links at top of section

- doc/style-guide/revision-history.rst
capitalization for job titles and team names
> Add updates to revision history

- doc/index.rst
- doc/retired-source-files-style-guide/README.rst
- doc/retired-source-files-style-guide/quickstart.rst
- doc/retired-source-files-style-guide/style/abbreviations.rst
- doc/retired-source-files-style-guide/style/capitalization.rst
- doc/retired-source-files-style-guide/style/code-examples.rst
- doc/retired-source-files-style-guide/writing/write-clear-concise-sentences-paragraphs.rst
the style guide https://developer.rackspace.com/docs/style-guide/
> Remove style guide for index and a link to the new location for

- doc/contributor-collateral/publiccloud-docteam-FAQ.rst
not sure about job titles or locations
> update team info

- doc/templates/ISSUE_TEMPLATE.md
> Remove defunct feedback.rackspace link

- doc/contributor-collateral/publiccloud-docteam-FAQ.rst
- doc/retired-source-files-style-guide/style/capitalization.rst
- doc/tools/GitHub-infra-templates/CONTRIBUTING-devdoc.md
- doc/tools/GitHub-infra-templates/README-devdoc.md
Identity as requested by the Identity dev team
> Change all occurrences of Rackspace Identity and Cloud Identity to
